spring.application.name=UsageService
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/energycommunitydb
spring.datasource.username=disysuser
spring.datasource.password=disyspw
spring.datasource.driver-class-name=org.postgresql.Driver

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin