name: disys-energycommunities

services:
  database:
    image: postgres:alpine
    container_name: postgres
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - database-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=disysuser
      - POSTGRES_PASSWORD=disyspw
      - POSTGRES_DB=energycommunitydb

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'
    environment:
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_USER: admin
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

volumes:
  database-data:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local