spring.application.name=JavaFxGuiAPI
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/energycommunitydb
spring.datasource.username=disysuser
spring.datasource.password=disyspw
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true